name: ktlr
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  dio: ^5.9.0
  dartz: ^0.10.1
  get_it: ^8.2.0
  flutter_svg: ^2.2.1
  cached_network_image: ^3.4.1
  google_fonts: ^6.3.2
  lottie: ^3.3.1
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/ic_splash.jpg"
  min_sdk_android: 21

  # Android adaptive icon
  adaptive_icon_background: "#202020"
  adaptive_icon_foreground: "assets/ic_splash.jpg"

  # iOS settings
  remove_alpha_ios: true

  # Web settings
  web:
    generate: true
    image_path: "assets/ic_splash.jpg"
    background_color: "#202020"
    theme_color: "#202020"

  # Windows settings
  windows:
    generate: true
    image_path: "assets/ic_splash.jpg"
    icon_size: 48

  # macOS settings
  macos:
    generate: true
    image_path: "assets/ic_splash.jpg"